name: CI

on:
  workflow_dispatch:
  schedule:
    - cron:  0 1,5,9,13,17,21 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ductnn/github-profile-terminal-action@main
      with:
        twitter_username: ductn4
        theme: dark
        token: ${{ secrets. GITHUB_TOKEN }}
        extra_repo: grafana/loki
